TransbankDevelopers/transbank-sdk-java

README.md

The previous version used "test purposes" as the description. 
Which is confusing, given that there is a TEST environment too.

Clarify the purpose of the MOCK environment

---

CHANGELOG.md
README.md
pom.xml
src/main/java/cl/transbank/onepay/Onepay.java
src/main/java/cl/transbank/onepay/model/Transaction.java
src/main/java/cl/transbank/onepay/util/OnepayRequestBuilder.java
src/main/java/cl/transbank/onepay/util/RequestBuilder.java
src/test/java/cl/transbank/onepay/model/test/OnepayRequestBuilderTest.java
src/test/java/cl/transbank/onepay/model/test/TransactionTest.java

Allow commerce to provide its own External Unique Number

---

README.md

Be more clear on how to use the `channel` param and when it is
necesary to set the callbackUrl

Impove readme file

---

.travis.yml

following suggestions in: https://github.com/travis-ci/travis-ci/issues/6593

Mark project as Sudo Required

---

src/main/java/cl/transbank/exception/TransbankException.java
src/main/java/cl/transbank/onepay/Onepay.java
src/test/java/cl/transbank/onepay/model/test/OnepayTest.java

This make it easy for integrators to start working against the TEST
environment without getting their own key and secret. It also enables
us to update the keys and easily distribute them if Transbank decides
to change them in the future.
It also includes an internal change on TransbankException because I 
found the issue when writing the test for this feature.

Preconfigured credentials

---

CHANGELOG.md
README.md
pom.xml

The full diff: https://github.com/TransbankDevelopers/transbank-sdk-java/compare/v1.3.1...chore/prepare-relase-1.4.0

Prepare release 1.4.0

---

CHANGELOG.md
README.md
pom.xml

See full diff at: https://github.com/TransbankDevelopers/transbank-sdk-java/compare/v1.4.0...prepare-relase-1.5.0

Prepare release 1.5.0

---

src/main/java/cl/transbank/onepay/Onepay.java
src/test/java/cl/transbank/onepay/model/test/ShoppingCartTest.java

- Test case for checking the cart with item with negative amount
- Test case for checking validation when the total amount is negative

Add test for checking edge case

---

CHANGELOG.md
README.md
pom.xml

See full diff at https://github.com/TransbankDevelopers/transbank-sdk-java/compare/v1.5.1...chore/prepare-release-1.5.2

Prepare release 1.5.2

---

CHANGELOG.md
README.md
pom.xml

See full diff at https://github.com/TransbankDevelopers/transbank-sdk-java/compare/v1.5.2...chore/prepare-release-1.5.3

Prepare release 1.5.3

---

CHANGELOG.md
README.md
pom.xml

You can see full changes here https://github.com/TransbankDevelopers/transbank-sdk-java/compare/v1.5.3...chore/prepare-release-1.6.0

Prepare release 1.6.0

---

src/main/java/cl/transbank/webpay/configuration/Configuration.java

The PatPass certs were updated for commerce code `597044444432`.

PatPass certs updated for 597044444432

---

CHANGELOG.md
README.md
pom.xml

You can see full changes here https://github.com/TransbankDevelopers/transbank-sdk-java/compare/v1.6.0...chore/prepare-release-1.6.1

Prepare release 1.6.1

---

src/main/java/cl/transbank/util/HttpUtil.java
src/main/java/cl/transbank/util/HttpUtilImpl.java
src/main/java/cl/transbank/webpay/Options.java
src/main/java/cl/transbank/webpay/WebpayApiResource.java
src/main/java/cl/transbank/webpay/exception/TransactionCreateException.java
src/main/java/cl/transbank/webpay/webpayplus/TransactionCreateRequest.java
src/main/java/cl/transbank/webpay/webpayplus/TransactionCreateResponse.java
src/main/java/cl/transbank/webpay/webpayplus/WebpayPlus.java
src/main/java/cl/transbank/webpay/webpayplus/model/CreateWebpayPlusTransactionResponse.java

Implement WebpayPlus.create

---

src/main/java/cl/transbank/webpay/webpayplus/WebpayPlus.java

There was a typo in a method name

Fix typo Webpay Plus buildOptions

---

src/main/java/cl/transbank/transaccioncompleta/FullTransaction.java
src/main/java/cl/transbank/transaccioncompleta/TransactionCreateRequest.java
src/main/java/cl/transbank/transaccioncompleta/model/FullTransactionCreateResponse.java
src/main/java/cl/transbank/webpay/webpayplus/WebpayPlus.java
src/test/java/cl/transbank/webpay/ConsoleExamples.java

Add TransaccionCompleta create

Add TransaccionCompelta.create

---

src/main/java/cl/transbank/WebpayApiResponseManager.java
src/main/java/cl/transbank/transaccioncompleta/FullTransaction.java
src/main/java/cl/transbank/transaccioncompleta/TransactionInstallmentRequest.java
src/main/java/cl/transbank/transaccioncompleta/model/FullTransactionInstallmentResponse.java
src/main/java/cl/transbank/webpay/exception/TransactionInstallmentException.java
src/test/java/cl/transbank/webpay/ConsoleExamples.java

Add Installments transaction on TransaccionCompleta

Add TransaccionCompleta.installments

---

src/main/java/cl/transbank/transaccioncompleta/FullTransaction.java
src/main/java/cl/transbank/transaccioncompleta/model/FullTransactionStatusResponse.java
src/main/java/cl/transbank/webpay/webpayplus/WebpayPlus.java
src/test/java/cl/transbank/webpay/ConsoleExamples.java

Add status on transaccion completa

Add status transaction on TransaccionCompleta

---

src/main/java/cl/transbank/model/MallTransactionCreateDetails.java
src/main/java/cl/transbank/transaccioncompleta/FullTransactionMall.java
src/main/java/cl/transbank/transaccioncompleta/MallFullTransaction.java
src/main/java/cl/transbank/transaccioncompleta/MallTransactionCreateRequest.java
src/main/java/cl/transbank/transaccioncompleta/model/FullTransactionMallCreateResponse.java
src/main/java/cl/transbank/transaccioncompleta/model/MallFullTransactionCreateResponse.java
src/main/java/cl/transbank/webpay/webpayplus/WebpayPlus.java
src/test/java/cl/transbank/webpay/ConsoleExamples.java

Added create transaction on Transaccion completa mall, expected parameters buyOrder(string), sessionId(String),cardNumber(String),cardExpirationDate(String) and a List of Details amount(double),commerceCode(String) and buyOrder(String). Response object, token (String). Also moved MallTransaccionCreateDetails. from Webpayplus to a common package.

Add create transaction on Transaccion Completa Mall”

---

src/main/java/cl/transbank/transaccioncompleta/MallFullTransaction.java
src/main/java/cl/transbank/transaccioncompleta/MallTransactionInstallmentRequest.java
src/main/java/cl/transbank/transaccioncompleta/model/MallFullTransactionInstallmentResponse.java

Added Installment transaccion on Transaccion Completa mall, expected parameters token(String), installmentsNumber(byte), buyOrder(String) and commerceCode(String), expected response installmentsAmount(double), idQueryInstallments(Long) and a List of DeferredPeriod, amount(double) and period(byte)

Add installmet transaction on Transaccion Completa Mall

---

src/main/java/cl/transbank/transaccioncompleta/FullTransaction.java
src/main/java/cl/transbank/transaccioncompleta/MallFullTransaction.java
src/main/java/cl/transbank/transaccioncompleta/MallFullTransactionCommitRequest.java
src/main/java/cl/transbank/transaccioncompleta/MallFullTransactionCreateRequest.java
src/main/java/cl/transbank/transaccioncompleta/MallFullTransactionInstallmentRequest.java
src/main/java/cl/transbank/transaccioncompleta/TransactionCommitRequest.java
src/main/java/cl/transbank/transaccioncompleta/model/MallFullTransactionCommitResponse.java
src/main/java/cl/transbank/transaccioncompleta/model/MallTransactionCommitDetails.java
src/test/java/cl/transbank/webpay/ConsoleExamples.java

Added commit transaction on Transaccion Completa mall, expected parameters: a list of long idQueryInstallments, byte deferredPeriodIndex, boolean gracePeriod, String commerceCode and String buyOrder

Add commit transaction on Transaccion Completa mall

---

src/main/java/cl/transbank/transaccioncompleta/MallFullTransaction.java
src/main/java/cl/transbank/transaccioncompleta/model/MallFullTransactionStatusResponse.java
src/test/java/cl/transbank/webpay/ConsoleExamples.java

Added status transaction for Transaccion Completa Mall, expected parameters, token (String)

Add status transaction on Transaccion Completa

---

src/main/java/cl/transbank/transaccioncompleta/MallFullTransaction.java
src/main/java/cl/transbank/transaccioncompleta/MallFullTransactionRefundRequest.java
src/main/java/cl/transbank/transaccioncompleta/model/MallFullTransactionRefundResponse.java
src/test/java/cl/transbank/webpay/ConsoleExamples.java

Added refund transaction on transaccion completa mall, expected parameters, token (String), amount (double), commerceCode(String) and buyOrder(String)

Add refund transaction on Transaccion Completa Mall

---

src/main/java/cl/transbank/patpass/PatpassComercio.java
src/main/java/cl/transbank/patpass/PatpassComercioInscriptionStartRequest.java
src/main/java/cl/transbank/patpass/PatpassComercioTransactionStatusRequest.java
src/main/java/cl/transbank/patpass/model/PatpassComercioTransactionStatusResponse.java
src/test/java/cl/transbank/webpay/ConsoleExamples.java

Added method to obtain the transaction status for Patpass Comercio

Add status transaction on Patpass comercio

---

src/main/java/cl/transbank/WebpayApiResponseManager.java
src/main/java/cl/transbank/common/IntegrationTypeHelper.java
src/main/java/cl/transbank/patpass/PatpassComercio.java
src/main/java/cl/transbank/patpass/PatpassComercioInscriptionStartRequest.java
src/main/java/cl/transbank/patpass/model/PatpassComercioTransactionStatusResponse.java

Add url for integration (test) and set default options to Test

Add Integration (test) on Patpass comercio

---

CHANGELOG.md
README.md
pom.xml

You can see full changes here [v1.6.1...chore/prepare-release-1.7.0](https://github.com/TransbankDevelopers/transbank-sdk-java/compare/v1.6.1...chore/prepare-release-1.7.0)

Prepare release 1.7.0

---

README.md
src/main/java/cl/transbank/webpay/oneclick/model/OneclickMallTransactionAuthorizeResponse.java

The param was already being deserialized, so it was only missing from the Authorization response.

Add Oneclick Mall missing param

---

CHANGELOG.md
README.md
pom.xml

You can see full diff here: https://github.com/TransbankDevelopers/transbank-sdk-java/compare/v1.7.0...feat/prepare-release-1.7.1

Prepare release 1.7.1

---

CHANGELOG.md
README.md
pom.xml

Full diff https://github.com/TransbankDevelopers/transbank-sdk-java/compare/v1.7.1...feat/prepare-release-1.8.0
This releae adds support for:
- Webpay Plus Rest
- modalidad normal
- modalidad captura diferida
- modalidad mall
- modalidad mall captura diferida
- Patpass by Webpay Rest
- Patpass Comercio Rest
- Transacción completa Rest
- modalidad mall

Prepare release 1.8.0

---

CHANGELOG.md
README.md
pom.xml

Fill diff https://github.com/TransbankDevelopers/transbank-sdk-java/compare/v1.8.0...chore/prepare-release-1.8.1

Prepare release 1.8.1

---

CHANGELOG.md
README.md
pom.xml

Prepare release 1.9.0
Full diff: https://github.com/TransbankDevelopers/transbank-sdk-java/compare/v1.8.1...chore/prepare-release-1.9.0

Prepare release 1.9.0

---

.travis.yml
README.md
pom.xml
src/main/java/cl/transbank/transaccioncompleta/FullTransaction.java
src/main/java/cl/transbank/transaccioncompleta/MallFullTransaction.java
src/main/java/cl/transbank/transaccioncompleta/MallFullTransactionCaptureRequest.java
src/main/java/cl/transbank/transaccioncompleta/TransactionCaptureRequest.java
src/main/java/cl/transbank/transaccioncompleta/model/FullTransactionCaptureResponse.java
src/main/java/cl/transbank/transaccioncompleta/model/MallFullTransactionCaptureResponse.java
src/test/java/cl/transbank/webpay/ConsoleExamples.java

Added class and methods to support deferred capture on Full transaction normal and mall.

Added support Deferred Capture

---

CHANGELOG.md

Full diff https://github.com/TransbankDevelopers/transbank-sdk-java/compare/chore/prepare-release-1.9.0...chore/prepare-release-1.9.1

Prepare release 1.9.1

---

CHANGELOG.md
README.md
pom.xml

Full diff: https://github.com/TransbankDevelopers/transbank-sdk-java/compare/v1.9.0...chore/prepare-release-1.9.3

Prepare release 1.9.3

---

CHANGELOG.md
README.md
pom.xml

https://github.com/TransbankDevelopers/transbank-sdk-java/compare/v1.9.3...chore/prepare-release-2.0.0

Chore/prepare release 2.0.0

---

CHANGELOG.md
README.md
pom.xml

Full diff https://github.com/TransbankDevelopers/transbank-sdk-java/compare/v2.0.0...chore/prepare-release-3.0.0

add 3.0.0 changelog

---

CHANGELOG.md
README.md
pom.xml

full diff https://github.com/TransbankDevelopers/transbank-sdk-java/compare/v3.0.0...master

add 3.0.1 changelog

---

CHANGELOG.md
pom.xml

Full diff: https://github.com/TransbankDevelopers/transbank-sdk-java/compare/v3.0.1...master

add 4.0.0 changelog

---

CHANGELOG.md
README.md
pom.xml

Update files to prepare release 1.9.5

Update version files for release 1.9.5

---

src/main/java/cl/transbank/webpay/oneclick/responses/OneclickMallTransactionAuthorizeResponse.java
src/main/java/cl/transbank/webpay/oneclick/responses/OneclickMallTransactionStatusResponse.java
src/main/java/cl/transbank/webpay/transaccioncompleta/responses/FullTransactionStatusResponse.java
src/main/java/cl/transbank/webpay/transaccioncompleta/responses/MallFullTransactionStatusResponse.java
src/main/java/cl/transbank/webpay/webpayplus/responses/WebpayPlusMallTransactionStatusResponse.java
src/main/java/cl/transbank/webpay/webpayplus/responses/WebpayPlusTransactionStatusResponse.java

* remove capture expiration date attribute

feat: remove capture expiration date attribute

---

src/main/java/cl/transbank/model/MallTransactionCreateDetails.java
src/main/java/cl/transbank/model/Options.java
src/main/java/cl/transbank/patpass/PatpassByWebpay.java
src/main/java/cl/transbank/patpass/PatpassComercio.java
src/main/java/cl/transbank/patpass/responses/PatpassTransactionCreateDetails.java
src/main/java/cl/transbank/util/HttpUtilImpl.java
src/main/java/cl/transbank/webpay/transaccioncompleta/FullTransaction.java

This PR adds SSL Exception Handling to the `HttpUtilImpl.java` file for the methods `createSendingDataConnection` and `request`
> [!IMPORTANT]
> The PR https://github.com/TransbankDevelopers/transbank-sdk-java/pull/180 needs to be merged first before merging this PR.

fix: add ssl exception handling for kiuwan scans

---

src/main/java/cl/transbank/common/ApiConstants.java
src/main/java/cl/transbank/common/IntegrationApiKeys.java
src/main/java/cl/transbank/model/Options.java
src/main/java/cl/transbank/patpass/model/PatpassOptions.java
src/main/java/cl/transbank/util/HttpUtil.java
src/main/java/cl/transbank/util/HttpUtilImpl.java
src/main/java/cl/transbank/util/ValidationUtil.java
src/main/java/cl/transbank/util/WebpayApiResource.java
src/main/java/cl/transbank/webpay/common/WebpayOptions.java
src/main/java/cl/transbank/webpay/transaccioncompleta/FullTransaction.java
src/main/java/cl/transbank/webpay/transaccioncompleta/MallFullTransaction.java

This PR addresses `Sonar` issues.
https://github.com/TransbankDevelopers/transbank-sdk-java/assets/16856300/a4c4709f-3e98-44f3-b1dc-5692a4ca224b
https://github.com/TransbankDevelopers/transbank-sdk-java/assets/16856300/7073d8a4-97dc-44ce-9d6a-a46056ac9011
https://github.com/TransbankDevelopers/transbank-sdk-java/assets/16856300/66f55a54-1884-457e-a288-b71af6fa8964
https://github.com/TransbankDevelopers/transbank-sdk-java/assets/16856300/9bd6c083-be40-43a9-b3bb-93250d0d0133
https://github.com/TransbankDevelopers/transbank-sdk-java/assets/16856300/00a494d6-4b59-439a-b5af-6810451da846
https://github.com/TransbankDevelopers/transbank-sdk-java/assets/16856300/7caf432d-c432-48c2-bcd9-62541e6419cd
https://github.com/TransbankDevelopers/transbank-sdk-java/assets/16856300/2ab39c20-af29-49cd-987e-c6 …

fix: sonar adjustments

---

src/main/java/cl/transbank/common/ApiConstants.java
src/main/java/cl/transbank/util/HttpUtilImpl.java
src/main/java/cl/transbank/webpay/modal/WebpayModalTransaction.java
src/main/java/cl/transbank/webpay/oneclick/OneclickMallInscription.java
src/main/java/cl/transbank/webpay/transaccioncompleta/FullTransaction.java
src/main/java/cl/transbank/webpay/transaccioncompleta/MallFullTransaction.java
src/main/java/cl/transbank/webpay/webpayplus/WebpayMallTransaction.java
src/main/java/cl/transbank/webpay/webpayplus/WebpayTransaction.java
src/test/java/webpayplus/OneclickMallDeferredTest.java
src/test/java/webpayplus/OneclickMallTest.java
src/test/java/webpayplus/PatpassByWebpayTest.java
src/test/java/webpayplus/PatpassComercioTest.java
src/test/java/webpayplus/WebpayModalTest.java
src/test/java/webpayplus/WebpayPlusDeferredTest.java
src/test/java/webpayplus/WebpayPlusMallDeferredTest.java
src/test/java/webpayplus/WebpayPlusMallTest.java
src/test/java/webpayplus/WebpayPlusTest.java

This PR adds a new variable in the `API Constants` so we don't have duplicated code.

refactor: move variable to constants

---

pom.xml
src/main/java/cl/transbank/util/HttpUtilImpl.java
src/main/java/cl/transbank/webpay/oneclick/OneclickMallInscription.java
src/test/java/webpayplus/OneclickMallDeferredTest.java
src/test/java/webpayplus/OneclickMallTest.java
src/test/java/webpayplus/PatpassComercioTest.java
src/test/java/webpayplus/TestBase.java
src/test/java/webpayplus/WebpayPlusDeferredTest.java
src/test/java/webpayplus/WebpayPlusMallDeferredTest.java
src/test/java/webpayplus/WebpayPlusMallTest.java
src/test/java/webpayplus/WebpayPlusTest.java

* improved delete method
* update lombok library to 1.18.34

feat: improved delete method

---

pom.xml

chore: update lombok

---

src/main/java/cl/transbank/webpay/exception/QueryBinException.java
src/main/java/cl/transbank/webpay/oneclick/Oneclick.java
src/main/java/cl/transbank/webpay/oneclick/OneclickMallBinInfo.java
src/main/java/cl/transbank/webpay/oneclick/requests/QueryBinRequest.java
src/main/java/cl/transbank/webpay/oneclick/responses/OneclickMallQueryBinResponse.java
src/test/java/webpayplus/OneclickMallTest.java

This PR add the new method info bin for Oneclick.
- Add the info bin response.
- Add the info bin exception.
- Add the class to handle the info bin request.
- Add test for the new method.

feat: add info bin

---

pom.xml

chore: update jars

---

src/main/java/cl/transbank/common/BaseTransaction.java
src/test/java/webpayplus/OneclickTest.java

* add new tests for build methods

test: add oneclick test
